### ISSUE TITLE
PHP Fatal error:  Declaration of Symfony\Component\Cache\Adapter\ArrayAdapter::getItem($key): Psr\Cache\CacheItemInterface must be compatible with Symfony\Component\Cache\Adapter\AdapterInterface::getItem($key): Symfony\Component\Cache\CacheItem in /<<PKGBUILDDIR>>/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php on line 122

### ISSUE THREAD

**Issue by utkarsh2102** [utkarsh2102/symfony#1]
Hello @bryceharrington,

The following lines from the patch is still problematic as it results in:
```
KO src/Symfony/Bundle/FrameworkBundle
PHP Fatal error:  Declaration of Symfony\Component\Cache\Adapter\ArrayAdapter::getItem($key): Psr\Cache\CacheItemInterface must be compatible with Symfony\Component\Cache\Adapter\AdapterInterface::getItem($key): Symfony\Component\Cache\CacheItem in /<<PKGBUILDDIR>>/src/Symfony/Component/Cache/Adapter/ArrayAdapter.php on line 122
```

https://github.com/utkarsh2102/symfony/blob/761e4f40da2740f3b03b1037c85277bbf248b366/debian/patches/adapt-to-new-container-interface.patch#L115-L125

So basically we need to patch it with the "right" return type, which I'm not sure atm. So this one is a **TODO**. And then new failures that I am yet to investigate.

That said, most of the tests would now run; the command I've been using so far is:
`$ sbuild -s --force-orig-source --extra-package=/home/utkarsh/ubuntu/php8/php-cache-tag-intertop/php-cache-tag-interop_1.0.1-1ubuntu1_all.deb --extra-package=/home/utkarsh/ubuntu/php8/php-doctrine-bundle/php-doctrine-bundle_2.2.3-1ubuntu1_all.deb`
(but you've already uploaded the two packages so once they're available in the archive, you'll just need to run `sbuild`.)

**Comment by bryceharrington** [comment]
The type here is CacheItem, like in the interface prototype in src/Symfony/Component/Cache/Adapter/AdapterInterface.php

```
+++ b/src/Symfony/Component/Cache/Adapter/AdapterInterface.php                                                 
@@ -29,19 +29,19 @@                                                                                            
      *                                                                                                        
      * @return CacheItem                                                                                      
      */                                                                                                       
-    public function getItem($key);                                                                            
+    public function getItem($key): CacheItem;  
```

**Comment by utkarsh2102** [comment]
Awesome, thank you!
